# Problem 1

In [13]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0,10,5)
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
print(matris.reshape(5,1))
# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)

[1 9 8 4 0]
(5,)
[[1]
 [9]
 [8]
 [4]
 [0]]
1


# Problem 2

In [29]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.array(np.arange(1, 11, 2))
print(matris)
# 2 - Oluşturduğunuz matrisi parçalayın
a,b,c = np.split(matris, [1, 3])
print(a)
print(b)
print(c)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate((a,b,c)))

[1 3 5 7 9]
[1]
[3 5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [43]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.random.choice(np.arange(5, 101, 2), size=(10))
print(matris)
# 2 - matris'in özelliklerini inceleyin
print(matris.ndim)
print(matris.shape)
print(matris.size)
print(matris.dtype)


[71 87 95 65 45 87 73 57  7 69]
1
(10,)
10
int32
