# Problem 1 

In [15]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([5,4,3,2,1])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)
print(np.sort(a))

[1 2 3 4 5]
[1 2 3 4 5]


# Problem 2

In [27]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10,15,30,45,60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5,15)
print(b)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,100,5)
print(c)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print(d)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print(e)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0,100,5)
print(f)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10,30,size=5)
print(g)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.uniform(-1,1,10)
print(h)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
i = np.random.randint(10,50,size=(3,5))
print(i)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(i.sum(axis = 0))
print(i.sum(axis = 1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(i.max())
print(i.min())
print(i.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(i.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
k = np.random.randint(10,20,size=8)
print(k)
print(k[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(k[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(i[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(i[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(i[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(i**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
m = np.random.randint(-50,50,size=(3,5))
print((m>0)&(m % 2 == 0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 23 16 24 14]
[-0.32569893 -0.08521254 -0.31306084  0.55081358 -0.81449153 -0.2757987
  0.01919943  0.91394932  0.14562875  0.30442953]
[[19 34 19 36 39]
 [23 39 24 19 30]
 [44 33 19 28 24]]
[ 86 106  62  83  93]
[147 135 148]
44
19
28.666666666666668
10
[10 13 15 14 18 12 11 11]
[10 13 15]
[11 11 12 18 14 15 13 10]
[19 34 19 36 39]
24
[19 23 44]
[[ 361 1156  361 1296 1521]
 [ 529 1521  576  361  900]
 [1936 1089  361  784  576]]
[[False False False  True False]
 [False  True False False False]
 [False  True False False False]]
