In [1]:
# NUMPY
# klasik Yöntem
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[2, 6, 12, 20]


In [4]:
# Numpy ile
import numpy as np 
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


In [4]:
# .reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# .shape ile arraylerin boyutlarını öğrenebiliriz.
print(multi.shape)
print(x.shape)

(3, 3)
(9,)


In [8]:
# .ndim ile arraylerin boyut sayısını öğrenebiliriz.
print(x.ndim)
print(multi.ndim)

1
2


In [9]:
# Birleştirme (Concatenation)
# .concatenate() fonksiyonu ile birleştirme yapabiliriz.
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [12]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [14]:
# axis = 0 ise satır bazında birleştirme yapar.
# axis = 1 ise sütun bazında birleştirme yapar.
print(np.concatenate([a,a], axis=0))
print(np.concatenate([a,a], axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [15]:
# Array Ayırma (Splitting)
# .split() fonksiyonu ile array ayırma yapabiliriz.
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [16]:
a,b,c = np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [10]:
# .vsplit() fonksiyonu ile array yatay olarak ayırma yapabiliriz.
n = np.arange(16).reshape(4,4)
np.vsplit(n,[2])


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [11]:
# .hsplit() fonksiyonu ile array dikey olarak ayırma yapabiliriz.
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [22]:
# np.arange(start,stop,step) : Belli bir aralıkta sayıları oluşturmak için kullanılır.
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

In [8]:
# np.zeros() : 0 lardan oluşan bir numpy dizisi oluşturulması için kullanılır.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
# np.ones() : 1 lerden oluşan bir numpy dizisi oluşturulması için kullanılır.
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
# np.linspace() : Belli bir aralıkta sayıları oluşturmak için kullanlır.
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [7]:
np.random.randint(0,10,3)

array([1, 3, 6])

In [15]:
#import numpy as np
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npArray)
print(npMulti)
print(npMulti.sum(axis=1)) # yatayda toplar

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 45 145 245 345 445]


In [18]:
""" Numpy Array Özellikleri
ndim : Boyut sayısı
shape : Boyut bilgisi
size : Toplam eleman sayısı
dtype : Veri tipi
"""
a = np.random.randint(10,size = 10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[5 7 9 1 9 4 2 1 0 5]
1
(10,)
10
int32


In [22]:
# sort() : array sıralama
v = np.array([8,24,232,12,5,42,55])
v.sort()
print(v)

[  5   8  12  24  42  55 232]


In [27]:
m = np.random.normal(20,5,(3,3))
print(m)
print(np.sort(m,axis= 0))
print(np.sort(m,axis= 1))

[[20.32808211 18.12304381 24.5492931 ]
 [16.3251914  17.91027152 22.61732502]
 [15.08037162 17.78394358 24.82636809]]
[[15.08037162 17.78394358 22.61732502]
 [16.3251914  17.91027152 24.5492931 ]
 [20.32808211 18.12304381 24.82636809]]
[[18.12304381 20.32808211 24.5492931 ]
 [16.3251914  17.91027152 22.61732502]
 [15.08037162 17.78394358 24.82636809]]


In [34]:
# index ile elemanlara erişebiliriz.
a = np.random.randint(10,size = 10)
print(a[0])
a[0] = 100
print(a)

9
[100   1   7   1   5   6   4   1   8   0]


In [38]:
x = np.random.randint(10,size=(3,5))
print(x)
print(x[0,0])
print(x[1,1])
x[1,4] = 100
print(x)

[[5 5 0 8 9]
 [2 3 6 3 6]
 [7 5 4 6 4]]
5
3
[[  5   5   0   8   9]
 [  2   3   6   3 100]
 [  7   5   4   6   4]]


In [40]:
x[1,4] = 3.14
print(x)

[[5 5 0 8 9]
 [2 3 6 3 3]
 [7 5 4 6 4]]


In [48]:
# Slicing ile elemanlara erişmek (array alt kümelerine erişmek)
a = np.arange(20,30)
print(a[0:3])
print(a[:3])
print(a[3:])
print(a[1::2])
print(a[0::2])
print(a[2::2])

[20 21 22]
[20 21 22]
[23 24 25 26 27 28 29]
[21 23 25 27 29]
[20 22 24 26 28]
[22 24 26 28]


In [5]:
b = np.random.randint(10,size=[5,5])
print(b)

[[7 6 8 3 2]
 [5 7 7 7 7]
 [0 1 6 3 2]
 [5 4 6 4 9]
 [1 3 3 8 2]]


In [6]:
print(b[:,0]) # tüm satırlardaki 0. sütundaki değerleri yaz
print(b[:,1])
print(b[1,:])

[7 5 0 5 1]
[6 7 1 4 3]
[5 7 7 7 7]


In [7]:
print(b[0:2,0:3]) # satır ,sütun
print(b[::2,::2])

[[7 6 8]
 [5 7 7]]
[[7 8 2]
 [0 6 2]
 [1 3 2]]


In [8]:
# Alt küme üzerinde işlem yapmak
alt_b = b[0:3,0:2]
alt_b


array([[7, 6],
       [5, 7],
       [0, 1]])

In [9]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b

array([[100,   6],
       [  5, 200],
       [  0,   1]])

In [10]:
print(b)

[[100   6   8   3   2]
 [  5 200   7   7   7]
 [  0   1   6   3   2]
 [  5   4   6   4   9]
 [  1   3   3   8   2]]


In [13]:
# Fancy Index : Bir liste içine bu arrayden istediğimiz indisleri koyarak o indislerdeki verileri alabiliriz.
v = np.arange(0,30,3)
print(v)
yetgen = [1,3,5]
print(v[yetgen])

m = np.arange(9).reshape(3,3)
print(m)
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir,sutun])

[ 0  3  6  9 12 15 18 21 24 27]
[ 3  9 15]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]


In [19]:
# Koşullu Eleman İşlemleri
v = np.array([1,2,3,4,5])
print(v>3)
print(v[v>3])
print(v[v<3])
print(v[v<=3])
print(v[v!=3])
print(v[v==3])

[False False False  True  True]
[4 5]
[1 2]
[1 2 3]
[1 2 4 5]
[3]


In [33]:
# Matematiksel İşlemler
print(v * 2)
print(v + 2)
print(v * 5 / 10)
print(v ** 2)
print(np.subtract(v,3)) # Her birinden 3 çıkarıyor.
print(np.add(v,2)) # Her birine 2 ekliyor.
print(np.multiply(v,2)) # çarpma
print(np.divide(v,2)) # bölme
print(np.power(v,2)) # üs alma
print(np.mod(v,5)) # mod alma
print(np.absolute(v)) # mutlak değer
print(np.sin(360))
print(np.log(10))
# ?np

[ 2  4  6  8 10]
[3 4 5 6 7]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[-2 -1  0  1  2]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1 2 3 4 0]
[1 2 3 4 5]
0.9589157234143065
2.302585092994046


In [36]:
# İki Bilinmeyenli Denklem Çözümü
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
